language: r
r:
  - devel
sudo: false
cache: packages

r_packages:
  - knitr
  - devtools
  - methods
warnings_are_errors: false

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    - amahzarn@uncc.edu
